### ISSUE TITLE
urlpath missing in venim

### ISSUE THREAD

**Issue by ghost** [michaelaye/venim#3]
>>>from venim.akatsuki import ir2
Traceback (most recent call last):

  File "<ipython-input-1-9341ce1a7db7>", line 1, in <module>
    from venim.akatsuki import ir2

  File "C:\ProgramFiles\Anaconda3\lib\site-packages\venim\akatsuki\ir2.py", line 9, in <module>
    from urlpath import URL

ModuleNotFoundError: No module named 'urlpath'

**Comment by michaelaye** [comment]
ah, thanks, that needs to go to the requirements, sorry.

**Comment by michaelaye** [comment]
for a quick resolution on your side: "pip install urlpath". (there is no conda package).

**Comment by michaelaye** [comment]
this is why i need to quickly add self-executing tests then these things are caught much faster, as these tests are running on servers with fresh venim installs, not mine...

**Comment by michaelaye** [comment]
solved by ea59b28f5e7961675a190976a73842dc8269182e
